SUBROUTINE ANGLE(X,Y,I,J,K,TOP,BOTTOM)

  ! RETURNS NUMERATOR AND DENOMINATOR FOR (2COS(THETA))**2

  PARAMETER (LLEN=300)
  REAL*8 X,Y,SS,ST,TOP,BOTTOM
  DIMENSION X(0:LLEN),Y(0:LLEN),ID(4),SS(3)
  ID(1)=I
  ID(2)=J
  ID(3)=K
  ID(4)=I

  DO L=1,3
     SS(L)=(X(ID(L))-X(ID(L+1)))**2+(Y(ID(L))-Y(ID(L+1)))**2
  END DO

  IF(SS(2).LT.SS(1)) THEN
     ST=SS(1)
     SS(1)=SS(2)
     SS(2)=ST
  END IF

  IF(SS(3).LT.SS(1)) THEN
     ST=SS(1)
     SS(1)=SS(3)
     SS(3)=ST
  END IF
  TOP=(SS(2)+SS(3)-SS(1))*(SS(2)+SS(3)-SS(1))
  BOTTOM=SS(2)*SS(3)
  RETURN
END SUBROUTINE ANGLE
