SUBROUTINE AUGMEN(N,NL,NB,INDEXP,NP,LID,LPF,I,K,J)

  ! AUGMENTS SPOKE LIST FOR POINT I BY ADDING EDGE K AT START

  PARAMETER (LLEN=300)
  DIMENSION INDEXP(-1:LLEN),NP(-LLEN:LLEN),LID(7*LLEN),LPF(7*LLEN)

  NL=NL+1
  IF(NL.EQ.7*LLEN+1) CALL GARBAG(N,NL,NB,INDEXP,NP,LID,LPF,J)
  LID(NL)=K
  LPF(NL)=NP(I)
  NP(I)=NL
  RETURN
END SUBROUTINE AUGMEN
