SUBROUTINE DATOUT(N,INDEXP,X,Y,NP,LID,LPF,LES,LEE,LELS,LERS,NT)
  
  PARAMETER (LLEN=300)
  REAL*8 X,Y,ZDUMMY
  DIMENSION INDEXP(-1:LLEN),X(0:LLEN),Y(0:LLEN),NP(-LLEN:LLEN),LID(7*LLEN),&
       LPF(7*LLEN),LES(3*LLEN),LEE(3*LLEN),LELS(3*LLEN),LERS(3*LLEN),ID(LLEN)
  ZDUMMY=0.0
  NT=0
  WRITE(22,102) N

  ! CALLS DECODE, ORDER

  ! MAKE THE OUTPUT DATA FILE
  DO KK=1,N
     II=INDEXP(KK)
     CALL DECODE(LID,LPF,NP(II),ID,M)
     CALL ORDER(LES,LEE,LELS,LERS,M,ID,II)
     WRITE(22,102) II,X(II),Y(II),M,ZDUMMY

     DO L=1,M-1
        IF(ID(L).GT.II.AND.ID(L+1).GT.II) NT=NT+1
     END DO

     J=1
     IST=1
1    IFIN=MIN(M,25*J)
     WRITE(22,101) (ID(K),K=IST,IFIN)

     IF(M.GT.25*J) THEN
        J=J+1
        IST=IFIN+1
        GOTO 1
     END IF
  END DO
  RETURN
101 FORMAT(25I5)
102 FORMAT(I5,2(1X,F10.5),1X,I5,1X,F10.5)
END SUBROUTINE DATOUT
