SUBROUTINE DECODE(LID,LPF,JJ,ID,I)

  ! DECODES LINKED LIST INTO SEQUENTIAL LIST

  PARAMETER (LLEN=300)
  DIMENSION LID(7*LLEN),LPF(7*LLEN),ID(LLEN)

  J=JJ
  I=0
1 I=I+1
  ID(I)=LID(J)
  IF(LPF(J).EQ.0) RETURN
  J=LPF(J)
  GOTO 1
END SUBROUTINE DECODE
