SUBROUTINE DELETE(LID,LPF,NP,K)

  ! DELETES EDGE K

  PARAMETER (LLEN=300)
  DIMENSION LID(7*LLEN),LPF(7*LLEN)

  J=NP
  IF(LID(J).EQ.K) THEN
     NP=LPF(J)
     RETURN
  END IF
1 IF(LID(LPF(J)).EQ.K) THEN
     LPF(J)=LPF(LPF(J))
     RETURN
  END IF
  J=LPF(J)
  IF(J.NE.0) GOTO 1
  RETURN
END SUBROUTINE DELETE
