SUBROUTINE GARBAG(N,NL,NB,INDEXP,NP,LID,LPF,JP)

  ! GARBAGE COLLECTOR FOR LINKED LIST

  PARAMETER (LLEN=300)
  DIMENSION INDEXP(-1:LLEN),NP(-LLEN:LLEN),LID(7*LLEN),LPF(7*LLEN)

  ! SET THE EDGE INDEX OF EACH NON-VACANT LOCATION TO NEGATIVE
  NN=N
  IF(NP(INDEXP(N)).EQ.0) NN=N-1
  IF(JP.NE.0) LIDJ=LID(JP)
  NEG=0
  ! PRINT *, LID
  DO I=1-NB,NN
     J=NP(INDEXP(I))
1    NEG=NEG+1
     ! PRINT *, J
     LID(J)=-LID(J)
     J=LPF(J)
     IF(J.NE.0) GOTO 1
  END DO

  ! STOP IF THERE ARE NO VACANT LOCATIONS
  IF(NEG.GE.7*LLEN) THEN
     WRITE(6,100)
  ELSE

     ! GET FIRST VACANT LOCATION
     NX=NEXT(LID,0)
     IF(NX.LE.NEG) THEN

        ! TRANSFER ITEMS FROM NON-VACANT LOCATIONS TO VACANT LOCATIONS
        DO 6 I=1-NB,NN
           J=NP(INDEXP(I))
           JJ=0
           IF(J.LE.NEG) GOTO 5
           NP(INDEXP(I))=NX
4          LPF(NX)=LPF(J)
           LID(NX)=LID(J)
           IF(JJ.NE.0) LPF(JJ)=NX
           J=NX
           NX=NEXT(LID,NX)
           IF(NX.GT.NEG) GOTO 7
5          IF(LPF(J).EQ.0) GOTO 6
           JJ=J
           J=LPF(J)
           IF(J.GT.NEG) GOTO 4
           GOTO 5
6          CONTINUE
     END IF

     ! SET TO POSITIVE THE EDGE INDICES IN THE FIRST NEG LOCATIONS

7    DO J=1,NEG
        LID(J)=-LID(J)
     END DO

     NL=NEG+1

     DO J=NL,7*LLEN
        LID(J)=0
     END DO

     IF(JP.EQ.0) RETURN

     ! RESET POINTER JP
     DO L=1,NB
        JP=NP(1-L)
10      IF(LID(JP).EQ.LIDJ) RETURN
        JP=LPF(JP)
        IF(JP.NE.0) GOTO 10
     END DO

     WRITE(6,101)
  END IF
  STOP
100 FORMAT('ARRAY OVERFLOW FOR LINKED LIST (SUBROUTINE GARBAG)')
101 FORMAT('POINTER NOT RESET (SUBROUTINE GARBAG)')
END SUBROUTINE GARBAG
