PROGRAM VDIAB
  
  PARAMETER (LLEN=300)
  CHARACTER FNAME1*20,FNAME2*20!,SCONTR*1
  REAL*8 X,Y
  DIMENSION INDEXP(-1:LLEN),X(0:LLEN),Y(0:LLEN),NP(-LLEN:LLEN),LID(7*LLEN),&
       LPF(7*LLEN),LES(3*LLEN),LEE(3*LLEN),LELS(3*LLEN),LERS(3*LLEN)

  ! CALLS DATIN, DATOUT, SORT, VORONO

  ! VARIABLES
  ! LLEN	ARRAY DIMENSIONING PARAMETER
  ! FNAME1	INPUT FILE NAME
  ! FNAME2	OUTPUT FILE NAME
  ! N		NNUMBER OF ACTIVE POINTS
  ! NN		HIGHEST POINT INDEX
  ! NE		NUMBER OF ACTIVE EDGES
  ! NL		HIGHEST USED LOCATION IN LINKED LIST
  ! INDEXP(J)	INDEX FOR POINT NUMBER J (0<J<=N)
  ! X(I)	X-COORDINATE FOR POINT WITH INDEX I (0<I<=NN)
  ! Y(I)	Y-COORDINATE FOR POINT WITH INDEX I (0<I<=NN)
  ! NP(I)	POINTER TO 1ST EDGE IN SPOKE LIST WITH INDEX I
  ! NP(I)	POINTER TO 1ST EDGE IN BOUNDARY I (I=0)
  ! LID		LINKED LIST, EDGE INDICES
  ! LPF		LINKED LIST, POINTER FORWARD (=0 FOR END OF LIST)
  ! LES(I)	Start point foredge with index I (0<I<=NE)
  ! LEE(I)	Ende point for edge with index I (0<I<=NE)
  ! LELS(I)	Left side point for edge with index I (0<I<=NE)
  !		=0 if on boundary
  ! LERS(I)	Right side point for edge with index I (0<I<=NE)
  !		=0 if on boundary

  
  ! SET UP FILES
  !WRITE(6,201)
  !READ(5,103) FNAME1
  !WRITE(6,202)
  !READ(5,103) FNAME2
  FNAME1='input.dat'
  FNAME2='output.dat'
  OPEN(UNIT=21,FILE=FNAME1,STATUS='UNKNOWN')
  OPEN(UNIT=22,FILE=FNAME2,STATUS='UNKNOWN')

  ! READ INPUT FILE AND ORDER IN ASCENDING X ORDER
  CALL DATIN(N,INDEXP,X,Y)
  ! WRITE(6,206)
  ! READ(5,109) SCONTR
  CALL SORT(N,INDEXP,X)
  ! IF(SCONTR.NE.'Y') CALL SORT(N,INDEXP,X)

  ! MAKE THE VORONOI DIAGRAM
  !LPF(1)=0
  CALL VORONO(N,NN,NE,NL,INDEXP,X,Y,NP,LID,LPF,LES,LEE,LELS,LERS)

  ! WRITE THE OUTPUT FILE
  CALL DATOUT(N,INDEXP,X,Y,NP,LID,LPF,LES,LEE,LELS,LERS,NT)
  STOP

103 FORMAT(A20)
! 109 FORMAT(A1)
201 FORMAT('INPUT DATA FILE')
202 FORMAT('OUTPUT DATA FILE')
! 206 FORMAT('ARE THE POINTS SORTED? (Y/N)')
END PROGRAM VDIAB
