FUNCTION NEXT(LID,NX)
  
  ! RETURNS POINTER TO THE NEXT VACANT LOCATION
  
  PARAMETER (LLEN=300)
  DIMENSION LID(7*LLEN)

  DO I=NX+1,7*LLEN
     IF(LID(I).GE.0) THEN
        NEXT=I
        RETURN
     END IF
  END DO

  NEXT=7*LLEN+1
  RETURN
END FUNCTION NEXT
