SUBROUTINE ORDER(LES,LEE,LELS,LERS,I,ID,II)
  ! ORDERS THE SPOKE LIST FOR II IN A CLOCKWISE SENSE

  PARAMETER (LLEN=300)
  DIMENSION LES(3*LLEN),LEE(3*LLEN),LELS(3*LLEN),LERS(3*LLEN),ID(LLEN),&
       IDP(LLEN),IDR(LLEN)
  K=1

  DO L=1,I
     IF(LEE(ID(L)).NE.II) THEN
        IDP(L)=LEE(ID(L))
        IDR(L)=LERS(ID(L))
        IF(LELS(ID(L)).EQ.0) K=L
     ELSE
        IDP(L)=LES(ID(L))
        IDR(L)=LELS(ID(L))
        IF(LERS(ID(L)).EQ.0) K=L
     END IF
  END DO

  M=0
3 M=M+1
  ID(M)=IDP(K)
  IF(IDR(K).NE.0) THEN
     J=IDR(K)
     IDR(K)=0

     DO K=1,I
        IF(IDP(K).EQ.J) GOTO 3
     END DO
  END IF
  I=M
  RETURN
END SUBROUTINE ORDER
