LOGICAL FUNCTION SAME(X,Y,I,I1,I2,XT,YT)

  ! RETURNS TRUE IF I IS ON THE SAME SIDE AS (XT,YT) OF THE LINE JOINING
  ! I1 AND I2, OR IF EITHER IS ON THE SAME LINE

  PARAMETER (LLEN=300)
  REAL*8 X,Y,X21,Y21,A,B,XT,YT
  DIMENSION X(0:LLEN),Y(0:LLEN)

  X21=X(I2)-X(I1)
  Y21=Y(I2)-Y(I1)
  A=(Y(I)-Y(I1))*X21-(X(I)-X(I1))*Y21
  B=(YT-Y(I1))*X21-(XT-X(I1))*Y21
  IF(ABS(A).LT.1.D-5) A=0.D0
  IF(ABS(B).LT.1.D-5) B=0.D0
  IF(A*B.LT.0.0) THEN
     SAME=.FALSE.
  ELSE
     SAME=.TRUE.
  END IF
  RETURN
END FUNCTION SAME
